
name: lab1
channels: 
  - default
dependencies:
  - python=3.7
  - pip
  - pip:
      - pip-tools

# conda create --name intro python=3.6
# conda create --name intro && conda activate intro && conda install python=3.6

# conda env export > environment.yml
# conda env create -f environment.yml

# https://github.com/jazzband/pip-tools
# https://github.com/full-stack-deep-learning/fsdl-text-recognizer-project/blob/master/setup.md
# other flow 

# conda env create -f environment.yml
# pip-compile requirements.in && pip-compile requirements-dev.in
# pip-sync requirements.txt requirements-dev.txt